// Generated by tools/sync-ipc-contract.py; edit manager1.xml.
#[zbus::proxy(
    interface = "io.github.marius4lui.LinuxDrop.Manager1",
    default_service = "io.github.marius4lui.LinuxDrop",
    default_path = "/io/github/marius4lui/LinuxDrop"
)]
pub trait Manager {
    fn get_snapshot(&self) -> zbus::Result<String>;
    fn get_settings(&self) -> zbus::Result<String>;
    fn get_defaults(&self) -> zbus::Result<String>;
    fn update_peer_preferences(&self, peer_id: String, patch: String) -> zbus::Result<()>;
    fn forget_peer(&self, peer_id: String) -> zbus::Result<()>;
    fn export_diagnostics(&self) -> zbus::Result<String>;
    fn restart_backends(&self) -> zbus::Result<()>;
    fn stop_when_idle(&self) -> zbus::Result<()>;
    fn reset_settings(&self) -> zbus::Result<()>;
    fn get_diagnostics(&self) -> zbus::Result<String>;
    fn prepare_send(&self, paths: Vec<String>) -> zbus::Result<String>;
    fn prepare_send_files(
        &self,
        draft_id: String,
        entries: Vec<(String, zbus::zvariant::Fd<'_>)>,
    ) -> zbus::Result<String>;
    fn export_received_file(&self, path: String) -> zbus::Result<String>;
    fn resolve_receive_directory(
        &self,
        document_id: String,
        relative_path: String,
    ) -> zbus::Result<String>;
    fn discard_draft(&self, draft_id: String) -> zbus::Result<()>;
    fn create_download_offer(&self, draft_id: String) -> zbus::Result<String>;
    fn stop_download_offer(&self) -> zbus::Result<()>;
    fn receive_download_offer(&self, url: String) -> zbus::Result<String>;
    fn start_send(
        &self,
        draft_id: String,
        peer_id: String,
        protocol: String,
    ) -> zbus::Result<String>;
    fn accept_transfer(&self, id: String) -> zbus::Result<()>;
    fn accept_transfer_with_options(&self, id: String, options: String) -> zbus::Result<()>;
    fn provide_transfer_pin(&self, id: String, pin: String) -> zbus::Result<()>;
    fn run_hardware_diagnostic(&self, radio_id: String, channel: u16) -> zbus::Result<String>;
    fn get_recovery_status(&self) -> zbus::Result<String>;
    fn reject_transfer(&self, id: String) -> zbus::Result<()>;
    fn cancel_transfer(&self, id: String) -> zbus::Result<()>;
    fn clear_history(&self) -> zbus::Result<()>;
    fn set_visibility(&self, mode: String) -> zbus::Result<()>;
    fn update_settings(&self, patch: String) -> zbus::Result<()>;
    fn open_notch_preferences(&self) -> zbus::Result<()>;
    fn open_application(&self) -> zbus::Result<()>;
    #[zbus(signal)]
    fn changed(&self, revision: u64) -> zbus::Result<()>;
}
