[package]
name = "linuxdrop-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
client = ["dep:zbus"]

[dependencies]
linuxdrop-core = { path = "../linuxdrop-core" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
zbus = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true
futures-util.workspace = true

[[example]]
name = "check_contract"
required-features = ["client"]
