#!/usr/bin/env python3
"""Generate checked Rust/GJS Manager1 bindings from the canonical introspection XML."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
xml = (root / "crates/linuxdrop-ipc/manager1.xml").read_text()
node = ET.fromstring(xml)
interface = node.find("interface")
iface = interface.attrib["name"]
bus = iface.rsplit(".", 1)[0]
path = node.attrib["name"]
methods = interface.findall("method")
def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
def signature(method, direction):
    return "(" + "".join(arg.attrib["type"] for arg in method.findall("arg") if arg.get("direction", "in") == direction) + ")"
constants = {"BUS": bus, "PATH": path, "INTERFACE": iface, "APP_ID": bus + ".App"}
rust = "// Generated by tools/sync-ipc-contract.py; edit manager1.xml.\n"
for name, value in constants.items():
    rust += f"pub const {name}: &str = {json.dumps(value)};\n"
rust += "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum ManagerMethod {\n"
rust += "".join(f"    {method.attrib['name']},\n" for method in methods) + "}\n"
rust += "impl ManagerMethod {\n    pub fn from_name(name: &str) -> Option<Self> {\n        Some(match name {\n"
rust += "".join(f"            \"{m.attrib['name']}\" => Self::{m.attrib['name']},\n" for m in methods)
rust += "            _ => return None,\n        })\n    }\n    pub fn signatures(self) -> (&'static str, &'static str) {\n        match self {\n"
rust += "".join(f"            Self::{m.attrib['name']} => (\"{signature(m, 'in')}\", \"{signature(m, 'out')}\"),\n" for m in methods)
rust += "        }\n    }\n}\n"
proxy = "// Generated by tools/sync-ipc-contract.py; edit manager1.xml.\n"
proxy += f'#[zbus::proxy(interface = "{iface}", default_service = "{bus}", default_path = "{path}")]\npub trait Manager {{\n'
types = {"s": "String", "as": "Vec<String>", "q": "u16", "t": "u64", "a(sh)": "Vec<(String, zbus::zvariant::Fd<'_>)>"}
for method in methods:
    inputs = [a for a in method.findall('arg') if a.get('direction', 'in') == 'in']
    outputs = [a for a in method.findall('arg') if a.get('direction') == 'out']
    params = ''.join(f", {a.attrib['name']}: {types[a.attrib['type']]}" for a in inputs)
    result = types[outputs[0].attrib['type']] if outputs else '()'
    proxy += f"    fn {snake(method.attrib['name'])}(&self{params}) -> zbus::Result<{result}>;\n"
for signal in interface.findall('signal'):
    params = ''.join(f", {a.attrib['name']}: {types[a.attrib['type']]}" for a in signal.findall('arg'))
    proxy += f"    #[zbus(signal)]\n    fn {snake(signal.attrib['name'])}(&self{params}) -> zbus::Result<()>;\n"
proxy += "}\n"
js = "// Generated by tools/sync-ipc-contract.py; edit manager1.xml.\n"
for name, value in constants.items():
    js += f"export const {name} = {json.dumps(value)};\n"
js += f"export const MANAGER_XML = {json.dumps(xml)};\n"
js += "export const METHODS = Object.freeze(" + json.dumps({m.attrib['name']: [signature(m,'in'), signature(m,'out')] for m in methods}, indent=4) + ");\n"
outputs = {"crates/linuxdrop-ipc/src/generated.rs": rust, "crates/linuxdrop-ipc/src/proxy.rs": proxy, "extensions/gnome-shell/contract.js": js}
for name, value in outputs.items():
    if name.endswith('.rs'):
        value = subprocess.run(['rustfmt', '--edition', '2021', '--emit', 'stdout'], input=value, text=True, capture_output=True, check=True).stdout
    target = root / name
    if args.check:
        if not target.exists() or target.read_text() != value:
            raise SystemExit(f"Stale contract binding: {name}; run tools/sync-ipc-contract.py")
    else:
        target.write_text(value)
print(f"Manager1 contract: {len(methods)} methods, {len(interface.findall('signal'))} signal; bindings {'verified' if args.check else 'generated'}")
